// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vgpt-layouts/AIFirst.tsx": () => import("../components/mockups/vgpt-layouts/AIFirst.tsx"),
  "./components/mockups/vgpt-layouts/ActivityBar.tsx": () => import("../components/mockups/vgpt-layouts/ActivityBar.tsx"),
  "./components/mockups/vgpt-layouts/AgentFirst.tsx": () => import("../components/mockups/vgpt-layouts/AgentFirst.tsx"),
  "./components/mockups/vgpt-layouts/CommandCenter.tsx": () => import("../components/mockups/vgpt-layouts/CommandCenter.tsx"),
  "./components/mockups/vgpt-layouts/SplitBrain.tsx": () => import("../components/mockups/vgpt-layouts/SplitBrain.tsx"),
  "./components/mockups/vgpt-layouts/UnifiedBottom.tsx": () => import("../components/mockups/vgpt-layouts/UnifiedBottom.tsx")
};
