/**
 * orchestrator/types.ts -- Shared types for the VenomGPT orchestration layer.
 *
 * Defines the core structures used by the task router, planner, action router,
 * and run-state machine that together replace the previous single-loop approach.
 *
 * =====================================================================
 * RunState Type Overview
 * =====================================================================
 *
 * RunState is the central mutable execution state object for a single agent
 * task run. It is created by createRunState() at the start of every task and
 * updated by the action router after each step in the agent loop.
 *
 * Lifecycle:
 *   1. createRunState() initialises all fields to safe defaults.
 *   2. The agent loop advances step and transitions phase through:
 *        initializing -> [planning] -> executing -> [verifying|repairing] -> complete|failed
 *   3. The action router mutates tracking fields (filesRead, filesWritten,
 *      commandsRun, gateCounts, etc.) after every action.
 *   4. On completion the state is consumed for execution-summary telemetry.
 *
 * Field groups:
 *
 *   Phase and step control
 *     phase        - Current RunPhase in the state machine (see RunPhase union).
 *     step         - Monotonic counter incremented each loop iteration.
 *     maxSteps     - Effective ceiling (min of operator setting and profile cap).
 *     profile      - The ExecutionProfile governing resource limits and behaviour.
 *     plan         - Optional ExecutionPlan produced by the planning phase.
 *
 *   Resource tracking (enforced by gate checks in actionRouter)
 *     filesRead    - Set of distinct file paths read this session.
 *     filesWritten - Set of distinct file paths written this session.
 *     commandsRun  - Ordered list of all shell commands executed.
 *
 *   Failure and repair tracking
 *     lastActionType         - Type string of the most recent action (or null).
 *     lastActionFailed       - Whether the last action returned an error.
 *     consecutiveFailures    - Count of sequential failures (triggers repair nudge).
 *     consecutiveParseFailures - Count of sequential JSON/model parse failures.
 *
 *   Verification subsystem
 *     unverifiedWrites  - Files written since the last successful verification.
 *     verificationsDone - Total successful verification steps completed.
 *
 *   Telemetry and diagnostics
 *     shellReadsBlocked - Shell commands blocked as file-read bypass attempts.
 *     gateCounts        - Partial map of GateRejectionReason to count, used for
 *                         execution summary and debugging.
 *
 *   Runtime lifecycle (task-6 pass)
 *     sideEffectsObserved  - Classified side-effect entry per run_command.
 *     verificationLedger   - Evidence accumulator with quality ladder.
 *     runtimeSnapshots     - Before/after port-state snapshots for server commands.
 *     verificationQuality  - Ledger quality label, mirrored for fast gate checks.
 *
 * =====================================================================
 */

import type { SideEffectClass, SideEffectClassification } from "./sideEffectClassifier.js";
import type { RuntimeSnapshot, RuntimeDiff }              from "./runtimeLifecycle.js";
import { VerificationLedger }                             from "./verificationLedger.js";
import type { VerificationQuality }                       from "./verificationLedger.js";
import { createDependencyAnalysis }                       from "./dependencyClassifier.js";
import type { DependencyAnalysis, StepDependencyClass }   from "./dependencyClassifier.js";

export type { SideEffectClass, SideEffectClassification, RuntimeSnapshot, RuntimeDiff, VerificationQuality };
export type { DependencyAnalysis, StepDependencyClass };
export { VerificationLedger };

// --- Continuation chain types (task-8 pass) -----------------------------------

/**
 * A single step entry in the what-remains model.
 * Derived from the original plan vs. completed action history.
 */
export interface WhatRemainsStep {
  /** Step identifier derived from plan expectedChanges index or file path. */
  id: string;
  /** Human-readable label for this step. */
  label: string;
  /** Status of this step at the time of resume. */
  status: "completed" | "remaining" | "failed" | "blocked";
  /** Reason this step is failed/blocked, if applicable. */
  reason?: string;
  /**
   * Structured file path this step operates on (when the step is a file write).
   * Used for deterministic gate enforcement — do NOT derive from label string parsing.
   * Absent for non-file steps (e.g. agent "remaining work" text entries).
   */
  filePath?: string;
}

/**
 * The structured what-remains model produced at resume time.
 * Derived from the original plan steps minus confirmed-complete action history.
 * Never generated by narrative heuristics — always grounded in real prior state.
 */
export interface WhatRemains {
  /** Steps already confirmed complete (from action history). */
  completedSteps: WhatRemainsStep[];
  /** Steps still outstanding (from plan minus completed). */
  remainingSteps: WhatRemainsStep[];
  /** Steps that were attempted but failed or blocked. */
  failedSteps: WhatRemainsStep[];
  /** Source checkpoint ID and timestamp for auditability. */
  groundedFrom: {
    checkpointId: string;
    checkpointCreatedAt: string;
  };
}

/**
 * Continuation lineage embedded in API responses.
 * Populated only when the task is a genuine resumed continuation — never fabricated.
 */
export interface ContinuationLineage {
  /** True when this task is a structured continuation of a prior run. */
  isContinuation: true;
  /** Task ID of the run this continues from. */
  parentTaskId: string;
  /** Checkpoint ID that grounded this continuation. */
  originCheckpointId: string;
  /** Number of continuation hops from the original run (1 = first continuation). */
  ancestryDepth: number;
  /** The what-remains snapshot computed at resume time. */
  whatRemainedAtResume: WhatRemains;
}

/**
 * Full continuation chain record stored on a resumed RunState.
 * Carries all fields needed to identify, audit, and surface continuation truth.
 */
export interface ContinuationChain {
  /** Task ID of the immediate parent run. */
  parentTaskId: string;
  /** Checkpoint that grounded this continuation. */
  originCheckpointId: string;
  /** True when this is a structured continuation (vs. an unstructured retry). */
  isStructuredContinuation: true;
  /** How many continuation hops from the first run (1 = first continuation). */
  ancestryDepth: number;
  /** What-remains snapshot built at resume time from real prior state. */
  whatRemainedAtResume: WhatRemains;
  /** ISO timestamp of when the continuation was created. */
  resumedAt: string;
}

// --- Task categories -----------------------------------------------------------

export type TaskCategory =
  | "conversational"
  | "visual_describe"
  | "visual_report"
  | "visual_fix"
  | "visual_improve"
  | "visual_analyze"
  | "code_edit"
  | "code_verify"
  | "server_check"
  | "text_explain";

// --- Execution profile ---------------------------------------------------------

/**
 * Defines the behavioral constraints and strategy for a task category.
 * Each profile caps resource usage and enables/disables optional phases.
 */
export interface ExecutionProfile {
  category:       TaskCategory;
  /** Hard step ceiling for this profile -- overrides the operator maxSteps when lower. */
  maxSteps:       number;
  /** Max distinct file reads before the action router blocks additional reads. */
  maxFileReads:   number;
  /** Max distinct file writes allowed in this profile. */
  maxFileWrites:  number;
  /** If true, write_file is hard-blocked at the gate level (for zero-write profiles). */
  writesAllowed:  boolean;
  /** Max run_command actions allowed in this profile. 0 = no commands allowed. */
  maxCommands:    number;
  /** If true, the action router blocks done when there are unverified writes. */
  requiresVerify: boolean;
  /** If true, a structured planning model call fires before the main execution loop. */
  planningPhase:  boolean;
  /** Human-readable description of this profile (logged, shown as route event). */
  description:    string;
  /**
   * If true, the done gate blocks completion unless the verification ledger
   * shows at least 'runtime_confirmed' quality. Use for tasks that must
   * confirm a server is live (e.g. screenshot_task, server_check profiles).
   */
  requiresRuntimeProof?: boolean;
}

// --- Execution plan ------------------------------------------------------------

/**
 * Structured plan produced by the planning phase before the main loop.
 * Injected into the agent context as an explicit roadmap.
 */
export interface ExecutionPlan {
  goal:            string;
  approach:        string;
  filesToRead:     string[];
  expectedChanges: string[];
  verification:    string;
}

// --- Run phase state machine ---------------------------------------------------

/**
 * Explicit phase tracking for task execution.
 * Transitions: initializing -> [planning] -> executing -> [verifying|repairing] -> complete|failed
 *
 * task-9 additions:
 *   awaiting_approval  — halted at an approval gate; operator must act before the loop continues.
 *   selectively_blocked — some lanes were not approved in a selective decision; those lanes are held.
 *   approval_denied    — gate was explicitly denied; run has halted with this terminal/non-terminal state.
 *   operator_overridden — a step was skipped/denied/substituted by an operator override.
 */
export type RunPhase =
  | "initializing"
  | "planning"
  | "inspecting"
  | "executing"
  | "verifying"
  | "repairing"
  | "wrapping_up"
  | "complete"
  | "blocked"
  | "failed"
  | "awaiting_approval"
  | "selectively_blocked"
  | "approval_denied"
  | "operator_overridden";

// --- Gate rejection reason (must match actionRouter.ts) ------------------------

export type GateRejectionReason =
  | "shell_read_redundant"
  | "shell_read_cap_exceeded"
  | "redundant_read"
  | "read_cap_exceeded"
  | "write_cap_exceeded"
  | "write_class_blocked"
  | "command_cap_exceeded"
  | "post_verify_read_blocked"
  | "verification_required"
  | "runtime_proof_required"
  /** Blocked because the file was already written+confirmed in the prior continuation run. */
  | "continuation_step_already_completed";

// --- Side-effect entry (stored in RunState) ------------------------------------

/**
 * A single classified side-effect observation recorded during a task run.
 * Stored in RunState.sideEffectsObserved in execution order.
 */
export interface SideEffectEntry {
  command:         string;
  classification:  SideEffectClassification;
  timestamp:       number;
}

// --- Approval gate model (task-9 pass) ----------------------------------------

/**
 * A named approval checkpoint definition.
 * Registered in the ApprovalGateRegistry before a run starts (or inline via API).
 * When the agent loop reaches a checkpoint with a matching id, it halts the run
 * and transitions to the `awaiting_approval` phase.
 */
export interface ApprovalGate {
  /** Stable identifier for this checkpoint (e.g. "pre_file_write", "post_plan"). */
  id: string;
  /** Human-readable description shown to the operator. */
  description: string;
  /**
   * Optional list of lane/step-group IDs this gate applies to.
   * When non-empty, only those lanes are held at the gate; others may proceed.
   * When empty or absent, the gate applies to the entire run.
   */
  scopedLaneIds?: string[];
  /**
   * Optional explicit set of lane IDs covered by this gate.
   * Used by selective approval to compute which lanes are blocked.
   */
  laneIds?: string[];
  /**
   * Snapshot of the dispatch plan captured when this gate was raised.
   * Preserved so POST /approve-selective can run dependency-safety checks
   * even after parallelDispatcher has cleared lastDispatchPlan.
   */
  dispatchPlanSnapshot?: Map<string, import("../orchestrator/parallelDispatcher.js").DispatchableStep>;
  /** Gate lifecycle status. Set to "pending" when the gate is first raised. */
  status: "pending" | "approved" | "denied";
  /** ISO timestamp when an operator acted on the gate. Absent until decided. */
  decidedAt?: string;
  /**
   * Optional step number at which this gate should be automatically raised.
   * When absent, the gate fires immediately at the next step boundary after registration.
   */
  triggerAtStep?: number;
}

/**
 * A single approval decision recorded when an operator acts on a gate.
 */
export interface ApprovalDecision {
  checkpointId: string;
  decision:     "approved" | "denied" | "selective";
  /** ISO timestamp of when the decision was made. */
  decidedAt:    string;
  /** For selective decisions: the subset of lane/step-group IDs approved to continue. */
  approvedLaneIds?: string[];
  /** Optional operator note. */
  note?:        string;
}

/**
 * A bounded override applied to a specific planned step.
 */
export interface OperatorOverride {
  stepId:    string;
  kind:      "skip" | "deny" | "substitute";
  /** For substitute overrides: the replacement step description or content hint. */
  substituteWith?: string;
  /** Optional operator note explaining the override. */
  note?:          string;
  /** ISO timestamp when the override was registered. */
  registeredAt:   string;
}

// --- Intervention kind ---------------------------------------------------------

/**
 * Signals the nature of the current intervention event on a live run.
 *   pause              — the run was explicitly paused by the operator; loop is waiting.
 *   blocked            — the agent called done with final_status "blocked".
 *   partial_proceed    — the operator accepted partial completion of a blocked task.
 *   awaiting_approval  — halted at an approval gate; waiting for operator decision.
 *   approval_denied    — gate was denied; run has transitioned to a denial state.
 *   null               — no active intervention.
 */
export type InterventionKind =
  | "pause"
  | "blocked"
  | "partial_proceed"
  | "awaiting_approval"
  | "approval_denied"
  | null;

// --- Run state -----------------------------------------------------------------

/**
 * Structured execution state that replaces scattered local variables in the
 * agent loop. Updated by the action router after each step.
 */
export interface RunState {
  phase:                    RunPhase;
  step:                     number;
  /** Effective max steps (min of operator setting and profile cap). */
  maxSteps:                 number;
  profile:                  ExecutionProfile;
  plan:                     ExecutionPlan | null;
  /** Distinct file paths that have been successfully read this session. */
  filesRead:                Set<string>;
  /** Distinct file paths that have been successfully written this session. */
  filesWritten:             Set<string>;
  /** All commands run (in order) -- used for evidence tracking at done. */
  commandsRun:              string[];
  lastActionType:           string | null;
  lastActionFailed:         boolean;
  /** Count of consecutive failed actions -- triggers repair-limit nudge. */
  consecutiveFailures:      number;
  consecutiveParseFailures: number;
  /** Files written since the last successful verification -- used for the verify gate. */
  unverifiedWrites:         Set<string>;
  /** Count of verification steps completed (successful run_command or read-back after write). */
  verificationsDone:        number;
  /**
   * Number of shell commands blocked because they were detected as file-read
   * bypass attempts (cat, sed -n, head, tail). Visible in logs for debugging.
   */
  shellReadsBlocked:        number;
  /**
   * Number of trivial verification commands (cat, echo, ls, pwd, etc.) that ran
   * after writes but did NOT clear unverifiedWrites due to insufficient quality.
   * Used for telemetry and to give the agent better guidance in the done gate.
   */
  trivialVerificationsBlocked: number;
  /** Gate trigger counts by rejection reason -- used for execution summary telemetry. */
  gateCounts:               Partial<Record<GateRejectionReason, number>>;
  /**
   * Append-only log of every phase transition, in order of occurrence.
   * Each entry records the phase name and the wall-clock ms when it was entered.
   * Re-entries (e.g. executing → repairing → executing) each get their own entry.
   * Included in the persisted execution summary as phaseTimeline.
   */
  phaseTransitions:         Array<{ phase: RunPhase; enteredAt: number }>;

  // ── Runtime lifecycle fields (task-6 pass) ────────────────────────────────────

  /** Ordered list of classified side-effect events, one per run_command action. */
  sideEffectsObserved:      SideEffectEntry[];
  /**
   * Per-task verification evidence ledger.
   * Accumulates static reads, command successes (by class), and runtime probes.
   * The ledger's quality label is the authoritative answer to "how well-proven is this?".
   */
  verificationLedger:       VerificationLedger;
  /**
   * Port-state snapshots captured around server_start/server_stop commands.
   * 'before' is taken immediately before the command; 'after' is taken after.
   * Multiple server commands in one task overwrite these fields (last wins).
   */
  runtimeSnapshots:         { before?: RuntimeSnapshot; after?: RuntimeSnapshot };
  /**
   * The ledger's current quality label, mirrored here for fast access without
   * calling ledger.getQuality() on every done-gate check.
   * Updated by updateStateAfterAction after each command.
   */
  verificationQuality:      VerificationQuality;
  /**
   * Accumulated dependency analysis for this run.
   * Updated by the agent loop immediately before each action is dispatched.
   * Persisted in the ExecutionSummary at task completion.
   */
  dependencyAnalysis:       DependencyAnalysis;

  // ── Continuation chain (task-8 pass) ──────────────────────────────────────

  /**
   * When this run was started via the resume-from-checkpoint path, this field
   * carries the full continuation lineage. Absent for normal (non-resumed) runs.
   */
  continuationChain?: ContinuationChain;

  // ── Repair cycle state (task-2 pass) ──────────────────────────────────────

  /**
   * Final repair cycle outcome, populated by the agent loop at each task exit point.
   * Driven by the RepairCycleState machine in agentLoop.ts — transitions occur ONLY
   * on orchestrator-observed verification events (ledger quality checks, gate rejections),
   * never from model narration or XML tags.
   *
   *   idle               — no verification failure was observed during this run
   *   verification_failed — at least one verification failure was observed
   *   repair_in_progress  — repair was actively being attempted (multiple failures)
   *   reverify_pending    — a repair succeeded; awaiting next verification
   *   passed              — re-verification produced quality > "none" after repair
   *   failed              — repair loop hit the cap with no pass
   *   partial             — hard cap forced partial completion
   *   inconclusive        — loop ended without definitive pass or fail evidence
   *
   * When absent (undefined), no repair cycle was engaged (normal completion).
   */
  repairCycleOutcome?:      string;

  // ── Intervention flags (task-16 pass) ─────────────────────────────────────

  /**
   * When true, the agent loop pauses at the next safe inter-step boundary
   * and spin-waits until this flag returns to false.  Set by the pause/resume
   * API endpoints; never set by the loop itself.
   */
  paused:                   boolean;
  /**
   * When true, the agent loop will call done with final_status "partial" at
   * the next safe inter-step boundary, even if the agent has not done so.
   * Only accepted when phase === "blocked".  Set by the proceed-as-partial
   * API endpoint.
   */
  partialProceed:           boolean;
  /**
   * Current intervention kind for this run.  Emitted with every live_phase
   * broadcast so the frontend can render context-appropriate controls.
   */
  interventionKind:         InterventionKind;
  /**
   * Optional human-readable context for why the task is blocked.
   * Derived from the `remaining` field of the agent's done action when
   * final_status === "blocked". Surfaced live in the LiveRunStateBar.
   */
  blockedContext:           string | null;

  // ── Approval gate fields (task-9 pass) ────────────────────────────────────

  /**
   * Named approval checkpoints active for this run.
   * Populated via the operator API before or during execution.
   * The agent loop checks this list at each step boundary.
   */
  approvalGates:            ApprovalGate[];
  /**
   * When set, the run is currently halted at this approval checkpoint ID.
   * The loop spins until an operator decision is recorded.
   */
  awaitingApproval:         string | null;
  /**
   * Accumulated approval decisions for this run (one per gate that was acted on).
   */
  approvalDecisions:        ApprovalDecision[];
  /**
   * Lane IDs that are selectively blocked (not approved in a selective decision).
   * The dispatcher reads this to skip those lane slots.
   * NOTE: This set is pruned by parallelDispatcher after each dispatch wave completes
   * to prevent cross-dispatch signal bleed. Use hadSelectiveBlock for final outcome truth.
   */
  selectivelyBlockedLaneIds: Set<string>;
  /**
   * Immutable outcome flag: set to true when any selective approval decision is made
   * (i.e., when approve-selective is called with at least one blocked lane).
   * Unlike selectivelyBlockedLaneIds (which is pruned per-dispatch), this flag persists
   * for the lifetime of the run and is used by resolveCleanExitReason to truthfully
   * classify the final exit as "selectively_blocked" even after dispatch cleanup.
   */
  hadSelectiveBlock: boolean;
  /**
   * Per-lane operator signals read by the parallel dispatcher before each wave.
   * Maps laneId → signal ("paused" | "cancelled" | "proceed").
   */
  laneControlSignals:       Map<string, "paused" | "cancelled" | "proceed">;
  /**
   * Registered operator overrides keyed by stepId.
   * Applied in the agent loop at the relevant step boundary.
   */
  operatorOverrides:        Map<string, OperatorOverride>;
  /**
   * Applied override records (subset of operatorOverrides that were executed).
   * Used to surface applied overrides in Evidence/Inspect.
   */
  appliedOverrides:         OperatorOverride[];
  /**
   * The most recently dispatched lane plan: maps laneId ("lane-N") → DispatchableStep.
   * Populated by parallelDispatcher before each wave so that approve-selective can
   * validate isolation/dependency safety against the real dispatch graph.
   * Only contains the current (or most recently completed) wave's lanes.
   */
  lastDispatchPlan:         Map<string, import("../orchestrator/parallelDispatcher.js").DispatchableStep>;
  /**
   * Active lane ID while a parallel dispatch wave is executing.
   * Set by agentLoop before dispatching into a lane; cleared after the wave.
   * When set, actionRouter passes this to verificationLedger.addEntry() so
   * VERIFY_RESULT records are tagged with the lane they belong to.
   */
  currentLaneId:            string | null;
  /**
   * P4 (task-9-closeout): Runtime snapshot captured at task start.
   * Used by the evidence assembler to compute the port diff against a
   * post-apply snapshot and to detect stale-runtime conditions.
   * Absent when runtime probing failed or was not attempted.
   */
  taskStartRuntimeSnapshot?: RuntimeSnapshot;

  /**
   * task-9: Per-lane execution summaries accumulated at parallel_join time.
   * Appended as each dispatch wave completes so evidence survives even if
   * event-cap pruning removes the raw parallel_join events before assembly.
   * Used by evidenceAssembler as the primary source for lane evidence; falls
   * back to deriveLaneEvidence(events) only when this array is empty.
   */
  parallelLaneSummaries: Array<{
    laneId: string;
    stepId: string;
    filePath: string;
    status: string;
    durationMs: number | null;
    error: string | null;
    verificationOutcome: string | null;
    dependencyClass: string | null;
    stepCount: number;
  }>;
}

export function createRunState(profile: ExecutionProfile, operatorMaxSteps: number): RunState {
  const now = Date.now();
  return {
    phase:                    "initializing",
    step:                     0,
    maxSteps:                 Math.min(operatorMaxSteps, profile.maxSteps),
    profile,
    plan:                     null,
    filesRead:                new Set(),
    filesWritten:             new Set(),
    commandsRun:              [],
    lastActionType:           null,
    lastActionFailed:         false,
    consecutiveFailures:      0,
    consecutiveParseFailures: 0,
    unverifiedWrites:         new Set(),
    verificationsDone:        0,
    shellReadsBlocked:        0,
    trivialVerificationsBlocked: 0,
    gateCounts:               {},
    phaseTransitions:         [{ phase: "initializing", enteredAt: now }],
    sideEffectsObserved:      [],
    verificationLedger:       new VerificationLedger(),
    runtimeSnapshots:         {},
    verificationQuality:      "none",
    dependencyAnalysis:       createDependencyAnalysis(),
    paused:                   false,
    partialProceed:           false,
    interventionKind:         null,
    blockedContext:           null,
    approvalGates:            [],
    awaitingApproval:         null,
    approvalDecisions:        [],
    selectivelyBlockedLaneIds: new Set(),
    hadSelectiveBlock:        false,
    laneControlSignals:       new Map(),
    operatorOverrides:        new Map(),
    appliedOverrides:         [],
    lastDispatchPlan:         new Map(),
    currentLaneId:            null,
    parallelLaneSummaries:    [],
  };
}

/**
 * Record a phase transition in the RunState.
 * Appends an entry to phaseTransitions for every transition, including re-entries.
 * Example: executing → repairing → executing produces three distinct entries.
 * No-ops if the requested phase is already active.
 */
export function recordPhaseTransition(state: RunState, newPhase: RunPhase): void {
  if (state.phase === newPhase) return;
  state.phase = newPhase;
  state.phaseTransitions.push({ phase: newPhase, enteredAt: Date.now() });
}
